apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "denodo.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "denodo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "denodo.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9999
            - containerPort: 9997
            - containerPort: 9996
            - containerPort: 9995
            - containerPort: 9090
          args: ["--vdpserver", "--designstudio", "--datacatalog"]
          env:
            - name: DENODO_WEBCONTAINER_STARTUP
              value: true