apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-sandbox" (include "denodo.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePortSandbox }}
      {{- end }}
  selector:
    app: {{ printf "%s-sandbox" (include "denodo.name" .) | trunc 63 | trimSuffix "-" }}